### ISSUE TITLE
aldt and gclat tagsets are different

### ISSUE THREAD

**Issue by gcelano** [alpheios-project/arethusa-configs#43]
the two tagsets for Latin are not the same: gclat allows annotation for the case for the gerund, while aldt does not. We want to keep gclat, this being the right one.

**Comment by balmas** [comment]
sorry Giuseppe, they are the same in the gitrepo, but looks like I forgot to deploy the updated aldt2lat.json with the change. This is live now. You may need to restart your browser/clear your cache to prompt arethusa to reload the file.
