### ISSUE TITLE
add INTRJ to harrington tag sets

### ISSUE THREAD

**Issue by balmas** [alpheios-project/arethusa-configs#56]
From @jmharrington : 
I would like to add one more tag to the "BASIC” drop-down menu under “APOS”;  the new tag would be “INTRJ” and stand for “interjection”.  Although relatively rare, these forms are meaningfully different that what is covered by AuxY.  Can you add that one tag?  Thanks.

@TDBuck can you take care of this?  I think maybe it needs to be on both the Latin and Greek harrington tags but I'm not sure.

**Comment by TDBuck** [comment]
#57 I just realized I missed the greek. going back to do it now

**Comment by TDBuck** [comment]
#58 is the real pull request. Let me know if anything needs further fixing.
